### ISSUE TITLE
Restarter

### ISSUE THREAD

**Issue by SirPlease** [LuckyServ/l4d2_luckylock_server_install_public#1]
Hi, the memory leaks that make a server restart necessary after every game have been resolved in the Competitive Rework you're basing this on. I recommend actually testing it out instead of forcefully restarting servers first, as this was also done to prevent less "crash logs" ending up in your included Accelerator extension.

**Comment by LuckyServ** [comment]
I suspect there are other memory leaks in Soucemod that we are unaware of. I also just don't trust that things get fully and properly reset after a config unload and want the server to reset to its original map. Better safe than sorry.

If you want a version of my plugin that doesn't spam the crash logs, I recommend you checkout the work done by [asik91au](https://github.com/asik91au/sourcemod-plugins/tree/master/source) on my server restarter plugin.

I don't mind spamming my crash logs with `sv_crash` and I made this plugin specifically to avoid dealing with weird bash scripts or cron jobs.
