### ISSUE TITLE
Elite config doesn't have sv_consistency_fixes.smx loaded + suggestion

### ISSUE THREAD

**Issue by theletterjwithadot** [LuckyServ/l4d2_luckylock_server_install_public#10]
Hi Lucky,

Would it be better if sv_consistency_fix.smx plugin is loaded from generalfixes.cfg as it applies to all config? (similar like how TickrateFixes.smx and other fixes are loaded via generalfixes.cfg)

After which, moving sv_consistency_fix.smx to optional/ will only require 1 copy of it instead of a copy in each config directory.

Regards,
J.

**Comment by SirPlease** [comment]
I'd like to add it should be in the regular plugins folder, not optional, as there's no reason not to apply this fix when configs aren't loaded.

**Comment by theletterjwithadot** [comment]
That would be a fantastic idea too.
