### ISSUE TITLE
2 plugins that should maybe be loaded as general fixes

### ISSUE THREAD

**Issue by theletterjwithadot** [LuckyServ/l4d2_luckylock_server_install_public#11]
Hi Lucky,

I feel that l4d_inaudible_ghosts.smx & musical_si.smx should be loaded as a general fix for all modes and even for the default mode too.

Regards,
J.

**Comment by LuckyServ** [comment]
I've put `l4d_inaudible_ghosts.smx` in generalfixes, but not `musical_si.smx`.
