### ISSUE TITLE
This is a really great thing

### ISSUE THREAD

**Issue by ivanlee93** [LuckyServ/l4d2_luckylock_server_install_public#13]
Hello, do the plug-ins you provide contain separate source code?I want to make a Chinese version and play with my friends.（Please excuse my English）

**Comment by LuckyServ** [comment]
The source the plugins can be found [here](https://github.com/LuckyServ/sourcemod-plugins). The `readyup.smx` used in all configs is the one provided by NextMod, which can be found [here](https://github.com/spoon-l4d2/Plugins/tree/master/source).
