### ISSUE TITLE
spawn order issue?

### ISSUE THREAD

**Issue by theletterjwithadot** [LuckyServ/l4d2_luckylock_server_install_public#15]
Hi Lucky,

I pushed your latest update and it seems there's double SI spawns for a default normal game. 
Like there's 2 boomers, 2 chargers etc. Not sure if it's related to the l4d2_fix_spawn_order plugin but just wanted to FYI you.

Regards,
J.

**Comment by LuckyServ** [comment]
Before I try to correct the issue, can you make sure you didn't have l4d2lib loaded twice?

**Comment by LuckyServ** [comment]
Tested l4d2_fix_spawn_order in the default config and it did not work properly. I instead only added the plugin to apex.

**Comment by SirPlease** [comment]
I'm curious as to how you tested it and when you ran into issues, as I currently still am running (and the Tournament is intended to run on) the plugin without complaints.
Also, are you using the one from my Github or the decompiled one posted earlier?

I strongly advise **not** adding it to other configs, as they're not tested on other configs. Also, your servers might be used for the Tournament and having the plugin loaded in a config where it's not supposed to be loaded can cause issues and a somewhat "unfair" environment.
