### ISSUE TITLE
whitelist.cfg not in directory

### ISSUE THREAD

**Issue by theletterjwithadot** [LuckyServ/l4d2_luckylock_server_install_public#9]
Hi Lucky,

Was just wondering if you were going to add the [whitelist.cfg](https://github.com/SirPlease/Server4Dead-Project/blob/master/Extensions%2C%20Gamedata%2C%20Competitive%20Preperation/whitelist.cfg) that was used in previous server setup guide by SirPlease as the default whitelist is rather ineffective with the sv_consistency_fix.smx plugin

Regards,
J.

**Comment by LuckyServ** [comment]
Good catch, the file has been added.

**Comment by SirPlease** [comment]
Pointless if the soundfiles themselves aren't added.

**Comment by theletterjwithadot** [comment]
Would [this](https://github.com/SirPlease/Server4Dead-Project/tree/master/Extensions%2C%20Gamedata%2C%20Competitive%20Preperation/sound) suffice?
